import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the filesystem, so adding a Markdown file to
 * `docs/` is all it takes to get it into the navigation. Ordering comes from
 * `sidebar_position` in each file's frontmatter and from the `position` field
 * in each category's `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
